# markdown
markdown: kramdown
kramdown:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: rouge

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Social Media Strategy FY17-20"
description: "The National Archives was founded in 1935 to preserve the records of the Federal Government and make them available to its citizens. Since then, we have grown to include 13 Presidential libraries and museums, multiple archival facilities, and educational centers located across the country. We reach millions of visitors and researchers each year at these locations."
baseurl: /social-media-strategy

# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
#org_name: usnationalarchives
org_name: usnationalarchives
repo_name: social-media-strategy
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Introduction
  url: /introduction/
- text: Vision
  url: /vision/
- text: Goals
  url: /goals/
  sub_navigation:
  - text: "Goal 1: Tell Great Stories"
    url: /goal1/

  - text: "Goal 2: Deepen Engagement"
    url: /goal2/
  - text: "Goal 3: Grow Our Audience"
    url: /goal3/
  - text: "Goal 4: Cultivate a Social Media Community of Practice"
    url: /goal4/

- text: Supporting Resources
  url: /resources/
- text: Sources
  url: /sources/
- text: Instructions for Feedback
  url: /feedback/



# sass
sass:
  sass_dir: _sass
